# Generated by Django 5.1.2 on 2025-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudiofile',
            name='recording_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
