# Generated by Django 5.1.7 on 2025-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudiofile',
            name='duration_seconds',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
