# Generated by Django 5.1.2 on 2025-02-20 16:32

import django.core.validators
import vocalization_management_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudiofile',
            name='audio_file',
            field=models.FileField(max_length=255, upload_to=vocalization_management_app.models.audio_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])]),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='audio_file_name',
            field=models.CharField(max_length=255),
        ),
    ]
