# Generated by Django 5.1.2 on 2025-02-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0002_alter_originalaudiofile_recording_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudiofile',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_audio', to='vocalization_management_app.animaltable'),
        ),
    ]
