# Generated by Django 5.1.6 on 2025-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0002_alter_originalaudiofile_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalaudiofile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unit number of the recording device', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='device_type',
            field=models.CharField(blank=True, help_text="e.g., 'SMM' for Song Meter Micro", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='full_device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Complete device identifier (e.g., SMM07257)', max_length=20, null=True),
        ),
    ]
