# Generated by Django 5.1.2 on 2025-02-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0003_alter_originalaudiofile_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudiofile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audio', to='vocalization_management_app.adminprofile'),
        ),
    ]
