# Generated by Django 5.1.6 on 2025-02-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0003_originalaudiofile_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectednoiseaudiofile',
            name='detected_noise_file_path',
        ),
        migrations.RemoveField(
            model_name='detectednoiseaudiofile',
            name='file_size_mb',
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Path to the folder containing this audio file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='week_folder',
            field=models.CharField(blank=True, help_text='Name of the weekly folder (YYYY-MM-DD_to_YYYY-MM-DD)', max_length=50, null=True),
        ),
    ]
