# Generated by Django 5.1.2 on 2025-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0004_alter_originalaudiofile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrogram',
            name='clip_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='clip_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrogram',
            name='is_full_audio',
            field=models.BooleanField(default=False),
        ),
    ]
