# Generated by Django 5.1.6 on 2025-02-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0004_remove_detectednoiseaudiofile_detected_noise_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalaudiofile',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='originalaudiofile',
            name='week_folder',
        ),
    ]
