# Generated by Django 5.1.6 on 2025-03-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0005_remove_originalaudiofile_folder_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalaudiofile',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='originalaudiofile',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='originalaudiofile',
            name='full_device_id',
        ),
        migrations.AddField(
            model_name='database',
            name='processing_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='processing_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectednoiseaudiofile',
            name='detected_noise_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detectednoiseaudiofile',
            name='file_size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
