# Generated by Django 5.1.2 on 2025-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0006_remove_originalaudiofile_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectednoiseaudiofile',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectednoiseaudiofile',
            name='magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
