# Generated by Django 5.1.2 on 2025-03-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0007_detectednoiseaudiofile_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalaudiofile',
            name='analysis_excel',
            field=models.FileField(blank=True, null=True, upload_to='analysis_excel/'),
        ),
    ]
