# Generated by Django 5.1.7 on 2025-03-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0006_processinglog'),
        ('vocalization_management_app', '0008_originalaudiofile_analysis_excel'),
    ]

    operations = [
    ]
