# Generated by Django 5.1.7 on 2025-03-26 15:55

from django.db import migrations


def check_and_create_column(apps, schema_editor):
    # Get the database connection
    connection = schema_editor.connection
    cursor = connection.cursor()
    
    # Check if the columns already exist
    cursor.execute("PRAGMA table_info(vocalization_management_app_spectrogram)")
    columns = [column[1] for column in cursor.fetchall()]
    
    # Add the columns if they don't exist
    if 'clip_end_time' not in columns:
        cursor.execute(
            "ALTER TABLE vocalization_management_app_spectrogram ADD COLUMN clip_end_time REAL NULL")
    
    if 'clip_start_time' not in columns:
        cursor.execute(
            "ALTER TABLE vocalization_management_app_spectrogram ADD COLUMN clip_start_time REAL NULL")
    
    if 'is_full_audio' not in columns:
        cursor.execute(
            "ALTER TABLE vocalization_management_app_spectrogram ADD COLUMN is_full_audio BOOL NOT NULL DEFAULT 0")


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0009_merge_20250326_1153'),
    ]

    operations = [
        migrations.RunPython(check_and_create_column),
    ]
