# Generated by Django 5.1.7 on 2025-03-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocalization_management_app', '0010_fix_duplicate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalaudiofile',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalaudiofile',
            name='sample_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originalaudiofile',
            name='zoo',
            field=models.ForeignKey(blank=True, choices=[('Breadsly_zoo', 'Breadsly Zoo')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_audio', to='vocalization_management_app.zoo'),
        ),
    ]
